# ── Active database: 4 cars ─────────────────────────────────────────────────
# Metadata (brand history, lineage, sales) lives in car_metadata.py — one entry
# per model, merged by main.py. Archived 27 models are in cars_data_archived.py.

_CRETA_COLORS = ['Atlas White', 'Abyss Black Pearl', 'Titan Grey', 'Stellar Silver', 'Fiery Red', 'Robust Amber', 'Mystic Olive', 'Stargazing Blue']
_CRETA_IMGS   = ['https://upload.wikimedia.org/wikipedia/commons/5/51/Moscow%2C_Hyundai_Creta_%282nd_gen%29_Aug_2025_01_%28cropped%29.jpg']
_XUV700_COLORS = ['Everest White', 'Midnight Black', 'Electric Blue', 'Dazzling Silver', 'Red Rage', 'Burnt Sienna', 'Deep Forest']
_XUV700_IMGS   = ['https://upload.wikimedia.org/wikipedia/commons/b/ba/2021_Mahindra_XUV700_2.2_AX7_%28India%29_front_view.png']
_NEXON_COLORS = ['Pristine White', 'Daytona Grey', 'Flame Red', 'Calgary White', 'Fearless Purple', 'Creative Ocean', 'Savannah Green', 'Dune']
_NEXON_IMGS   = ['https://upload.wikimedia.org/wikipedia/commons/2/25/Tata_Nexon_Blue_Dual_Tone.jpg']
_CITY_COLORS  = ['Lunar Silver Metallic', 'Platinum White Pearl', 'Radiant Red Metallic', 'Meteoroid Grey Metallic', 'Obsidian Blue Pearl', 'Crystal Black Pearl']
_CITY_IMGS    = {'Lunar Silver Metallic': '/images/honda-city-lunar-silver-metallic.jpg', 'Platinum White Pearl': '/images/honda-city-platinum-white-pearl.jpg', 'Radiant Red Metallic': '/images/honda-city-radiant-red-metallic.jpg', 'Meteoroid Grey Metallic': '/images/honda-city-meteoroid-grey-metallic.jpg', 'Obsidian Blue Pearl': '/images/honda-city-obsidian-blue-pearl.jpg', 'Crystal Black Pearl': '/images/honda-city-crystal-black-pearl.jpg'}

CARS_DATA = [
    {'id':1  , 'brand':'Hyundai'   , 'model_name':'Creta'   , 'series':'E'             , 'trim_name':'E 1.5 Petrol MT'                         , 'car_type':'SUV'           , 'fuel_type':'Petrol'  , 'gearbox_type':'Manual'    , 'ex_showroom_price':11.0  , 'power':113  , 'colors':_CRETA_COLORS, 'image_urls':_CRETA_IMGS},
    {'id':2  , 'brand':'Hyundai'   , 'model_name':'Creta'   , 'series':'EX'            , 'trim_name':'EX 1.5 Petrol MT'                        , 'car_type':'SUV'           , 'fuel_type':'Petrol'  , 'gearbox_type':'Manual'    , 'ex_showroom_price':12.0  , 'power':113  , 'colors':_CRETA_COLORS, 'image_urls':_CRETA_IMGS},
    {'id':3  , 'brand':'Hyundai'   , 'model_name':'Creta'   , 'series':'EX'            , 'trim_name':'EX 1.5 Diesel MT'                        , 'car_type':'SUV'           , 'fuel_type':'Diesel'  , 'gearbox_type':'Manual'    , 'ex_showroom_price':13.2  , 'power':114  , 'colors':_CRETA_COLORS, 'image_urls':_CRETA_IMGS},
    {'id':4  , 'brand':'Hyundai'   , 'model_name':'Creta'   , 'series':'S'             , 'trim_name':'S 1.5 Petrol MT'                         , 'car_type':'SUV'           , 'fuel_type':'Petrol'  , 'gearbox_type':'Manual'    , 'ex_showroom_price':13.16 , 'power':113  , 'colors':_CRETA_COLORS, 'image_urls':_CRETA_IMGS},
    {'id':5  , 'brand':'Hyundai'   , 'model_name':'Creta'   , 'series':'SX'            , 'trim_name':'SX 1.5 Petrol iVT'                       , 'car_type':'SUV'           , 'fuel_type':'Petrol'  , 'gearbox_type':'Automatic' , 'ex_showroom_price':15.82 , 'power':113  , 'colors':_CRETA_COLORS, 'image_urls':_CRETA_IMGS},
    {'id':6  , 'brand':'Hyundai'   , 'model_name':'Creta'   , 'series':'SX'            , 'trim_name':'SX 1.5 Diesel MT'                        , 'car_type':'SUV'           , 'fuel_type':'Diesel'  , 'gearbox_type':'Manual'    , 'ex_showroom_price':17.16 , 'power':114  , 'colors':_CRETA_COLORS, 'image_urls':_CRETA_IMGS},
    {'id':7  , 'brand':'Hyundai'   , 'model_name':'Creta'   , 'series':'SX(O)'         , 'trim_name':'SX(O) 1.5 Diesel AT'                     , 'car_type':'SUV'           , 'fuel_type':'Diesel'  , 'gearbox_type':'Automatic' , 'ex_showroom_price':20.15 , 'power':114  , 'colors':_CRETA_COLORS, 'image_urls':_CRETA_IMGS},
    {'id':8  , 'brand':'Hyundai'   , 'model_name':'Creta'   , 'series':'SX(O) Tech'    , 'trim_name':'SX(O) Tech 1.5 Turbo Petrol DCT'         , 'car_type':'SUV'           , 'fuel_type':'Petrol'  , 'gearbox_type':'Automatic' , 'ex_showroom_price':20.3  , 'power':158  , 'colors':_CRETA_COLORS, 'image_urls':_CRETA_IMGS},
    {'id':9  , 'brand':'Mahindra'  , 'model_name':'XUV 700' , 'series':'MX'            , 'trim_name':'MX 2.0 Petrol MT'                        , 'car_type':'SUV'           , 'fuel_type':'Petrol'  , 'gearbox_type':'Manual'    , 'ex_showroom_price':13.99 , 'power':197  , 'colors':_XUV700_COLORS, 'image_urls':_XUV700_IMGS},
    {'id':10 , 'brand':'Mahindra'  , 'model_name':'XUV 700' , 'series':'AX3'           , 'trim_name':'AX3 2.2 Diesel MT'                       , 'car_type':'SUV'           , 'fuel_type':'Diesel'  , 'gearbox_type':'Manual'    , 'ex_showroom_price':15.89 , 'power':182  , 'colors':_XUV700_COLORS, 'image_urls':_XUV700_IMGS},
    {'id':11 , 'brand':'Mahindra'  , 'model_name':'XUV 700' , 'series':'AX5'           , 'trim_name':'AX5 2.0 Petrol AT'                       , 'car_type':'SUV'           , 'fuel_type':'Petrol'  , 'gearbox_type':'Automatic' , 'ex_showroom_price':18.19 , 'power':197  , 'colors':_XUV700_COLORS, 'image_urls':_XUV700_IMGS},
    {'id':12 , 'brand':'Mahindra'  , 'model_name':'XUV 700' , 'series':'AX7'           , 'trim_name':'AX7 2.2 Diesel AT'                       , 'car_type':'SUV'           , 'fuel_type':'Diesel'  , 'gearbox_type':'Automatic' , 'ex_showroom_price':21.54 , 'power':182  , 'colors':_XUV700_COLORS, 'image_urls':_XUV700_IMGS},
    {'id':13 , 'brand':'Mahindra'  , 'model_name':'XUV 700' , 'series':'AX7L'          , 'trim_name':'AX7L 2.2 Diesel AT'                      , 'car_type':'SUV'           , 'fuel_type':'Diesel'  , 'gearbox_type':'Automatic' , 'ex_showroom_price':23.49 , 'power':182  , 'colors':_XUV700_COLORS, 'image_urls':_XUV700_IMGS},
    {'id':14 , 'brand':'Tata'      , 'model_name':'Nexon'   , 'series':'Smart'         , 'trim_name':'Smart 1.2 Petrol MT'                     , 'car_type':'Compact SUV'   , 'fuel_type':'Petrol'  , 'gearbox_type':'Manual'    , 'ex_showroom_price':8.15  , 'power':118  , 'colors':_NEXON_COLORS, 'image_urls':_NEXON_IMGS},
    {'id':15 , 'brand':'Tata'      , 'model_name':'Nexon'   , 'series':'Smart+'        , 'trim_name':'Smart+ 1.2 Petrol MT'                    , 'car_type':'Compact SUV'   , 'fuel_type':'Petrol'  , 'gearbox_type':'Manual'    , 'ex_showroom_price':9.3   , 'power':118  , 'colors':_NEXON_COLORS, 'image_urls':_NEXON_IMGS},
    {'id':16 , 'brand':'Tata'      , 'model_name':'Nexon'   , 'series':'Pure'          , 'trim_name':'Pure 1.5 Diesel MT'                      , 'car_type':'Compact SUV'   , 'fuel_type':'Diesel'  , 'gearbox_type':'Manual'    , 'ex_showroom_price':11.1  , 'power':113  , 'colors':_NEXON_COLORS, 'image_urls':_NEXON_IMGS},
    {'id':17 , 'brand':'Tata'      , 'model_name':'Nexon'   , 'series':'Pure+'         , 'trim_name':'Pure+ 1.5 Diesel MT'                     , 'car_type':'Compact SUV'   , 'fuel_type':'Diesel'  , 'gearbox_type':'Manual'    , 'ex_showroom_price':12.0  , 'power':113  , 'colors':_NEXON_COLORS, 'image_urls':_NEXON_IMGS},
    {'id':18 , 'brand':'Tata'      , 'model_name':'Nexon'   , 'series':'Creative'      , 'trim_name':'Creative 1.2 Petrol AMT'                 , 'car_type':'Compact SUV'   , 'fuel_type':'Petrol'  , 'gearbox_type':'Automatic' , 'ex_showroom_price':11.8  , 'power':118  , 'colors':_NEXON_COLORS, 'image_urls':_NEXON_IMGS},
    {'id':19 , 'brand':'Tata'      , 'model_name':'Nexon'   , 'series':'Creative+'     , 'trim_name':'Creative+ 1.5 Diesel AMT'                , 'car_type':'Compact SUV'   , 'fuel_type':'Diesel'  , 'gearbox_type':'Automatic' , 'ex_showroom_price':13.1  , 'power':113  , 'colors':_NEXON_COLORS, 'image_urls':_NEXON_IMGS},
    {'id':20 , 'brand':'Tata'      , 'model_name':'Nexon'   , 'series':'Fearless'      , 'trim_name':'Fearless 1.2 Petrol DCT'                 , 'car_type':'Compact SUV'   , 'fuel_type':'Petrol'  , 'gearbox_type':'Automatic' , 'ex_showroom_price':14.8  , 'power':118  , 'colors':_NEXON_COLORS, 'image_urls':_NEXON_IMGS},
    {'id':21 , 'brand':'Tata'      , 'model_name':'Nexon'   , 'series':'Fearless S'    , 'trim_name':'Fearless S 1.2 Petrol DCT S'             , 'car_type':'Compact SUV'   , 'fuel_type':'Petrol'  , 'gearbox_type':'Automatic' , 'ex_showroom_price':16.49 , 'power':118  , 'colors':_NEXON_COLORS, 'image_urls':_NEXON_IMGS},
    {'id':22 , 'brand':'Honda'     , 'model_name':'City'    , 'series':'V'             , 'trim_name':'V 1.5 Petrol MT'                         , 'car_type':'Sedan'         , 'fuel_type':'Petrol'  , 'gearbox_type':'Manual'    , 'ex_showroom_price':11.48 , 'power':119  , 'colors':_CITY_COLORS, 'image_urls':_CITY_IMGS},
    {'id':23 , 'brand':'Honda'     , 'model_name':'City'    , 'series':'V'             , 'trim_name':'V 1.5 Petrol CVT'                        , 'car_type':'Sedan'         , 'fuel_type':'Petrol'  , 'gearbox_type':'Automatic' , 'ex_showroom_price':12.98 , 'power':119  , 'colors':_CITY_COLORS, 'image_urls':_CITY_IMGS},
    {'id':24 , 'brand':'Honda'     , 'model_name':'City'    , 'series':'VX'            , 'trim_name':'VX 1.5 Petrol MT'                        , 'car_type':'Sedan'         , 'fuel_type':'Petrol'  , 'gearbox_type':'Manual'    , 'ex_showroom_price':13.98 , 'power':119  , 'colors':_CITY_COLORS, 'image_urls':_CITY_IMGS},
    {'id':25 , 'brand':'Honda'     , 'model_name':'City'    , 'series':'VX'            , 'trim_name':'VX 1.5 Petrol CVT'                       , 'car_type':'Sedan'         , 'fuel_type':'Petrol'  , 'gearbox_type':'Automatic' , 'ex_showroom_price':15.4  , 'power':119  , 'colors':_CITY_COLORS, 'image_urls':_CITY_IMGS},
    {'id':26 , 'brand':'Honda'     , 'model_name':'City'    , 'series':'ZX'            , 'trim_name':'ZX 1.5 Petrol CVT'                       , 'car_type':'Sedan'         , 'fuel_type':'Petrol'  , 'gearbox_type':'Automatic' , 'ex_showroom_price':15.42 , 'power':119  , 'colors':_CITY_COLORS, 'image_urls':_CITY_IMGS},
    {'id':27 , 'brand':'Honda'     , 'model_name':'City'    , 'series':'e:HEV'         , 'trim_name':'e:HEV 1.5 Strong Hybrid e-CVT'           , 'car_type':'Sedan'         , 'fuel_type':'Hybrid'  , 'gearbox_type':'Automatic' , 'ex_showroom_price':18.99 , 'power':126  , 'colors':_CITY_COLORS, 'image_urls':_CITY_IMGS},
]

