# ── Active database: 4 cars ─────────────────────────────────────────────────
# Metadata (brand history, lineage, sales) lives in car_metadata.py — one entry
# per model, merged by main.py. Archived 27 models are in cars_data_archived.py.

_CRETA_COLORS  = ['Robust Emerald Pearl', 'Atlas White With Titanium Black', 'Titanium Black Matte', 'Titan Grey Matte', 'Starry Night', 'Atlas White', 'Titan Grey', 'Titanium Black', 'King Limited Edition Titanium Black Matte']
_CRETA_IMGS    = {'Robust Emerald Pearl': '/images/hyundai-creta-robust-emerald-pearl.jpg', 'Atlas White With Titanium Black': '/images/hyundai-creta-atlas-white-with-titanium-black.jpg', 'Titanium Black Matte': '/images/hyundai-creta-titanium-black-matte.jpg', 'Titan Grey Matte': '/images/hyundai-creta-titan-grey-matte.jpg', 'Starry Night': '/images/hyundai-creta-starry-night.jpg', 'Atlas White': '/images/hyundai-creta-atlas-white.jpg', 'Titan Grey': '/images/hyundai-creta-titan-grey.jpg', 'Titanium Black': '/images/hyundai-creta-titanium-black.jpg', 'King Limited Edition Titanium Black Matte': '/images/hyundai-creta-king-limited-edition-titanium-black-matte.jpg'}
_CRETA_MIRROR  = True   # images face left — apply scaleX(-1) to face left consistently

_THAR_COLORS   = ['Everest White', 'Galaxy Grey', 'Stealth Black', 'Battleship Gray', 'Deep Forest', 'Tango Red']
_THAR_IMGS     = {'Everest White': '/images/mahindra-thar-everest-white.jpg', 'Galaxy Grey': '/images/mahindra-thar-galaxy-grey.jpg', 'Stealth Black': '/images/mahindra-thar-stealth-black.jpg', 'Battleship Gray': '/images/mahindra-thar-battleship-gray.jpg', 'Deep Forest': '/images/mahindra-thar-deep-forest.jpg', 'Tango Red': '/images/mahindra-thar-tango-red.jpg'}
_THAR_MIRROR   = True

_NEXON_COLORS  = ['Pure Grey Black Roof', 'Ocean Blue With White Roof', 'Pristine White', 'Daytona Grey Dual Tone', 'Atlas Black Dark Edition', 'Grassland Beige With Black Roof', 'Grassland Beige', 'Atlas Black Red Edition', 'Pristine White Dual Tone', 'Ocean Blue', 'Pure Grey', 'Royal Blue', 'Royal Blue With Black Roof', 'Daytona Grey']
_NEXON_IMGS    = {'Pure Grey Black Roof': '/images/tata-nexon-pure-grey-black-roof.jpg', 'Ocean Blue With White Roof': '/images/tata-nexon-ocean-blue-with-white-roof.jpg', 'Pristine White': '/images/tata-nexon-pristine-white.jpg', 'Daytona Grey Dual Tone': '/images/tata-nexon-daytona-grey-dual-tone.jpg', 'Atlas Black Dark Edition': '/images/tata-nexon-dark-edition-atlas-black.jpg', 'Grassland Beige With Black Roof': '/images/tata-nexon-grassland-beige-with-black-roof.jpg', 'Grassland Beige': '/images/tata-nexon-grassland-beige.jpg', 'Atlas Black Red Edition': '/images/tata-nexon-atlas-black-red-dark-edition.jpg', 'Pristine White Dual Tone': '/images/tata-nexon-pristine-white-dual-tone.jpg', 'Ocean Blue': '/images/tata-nexon-ocean-blue.jpg', 'Pure Grey': '/images/tata-nexon-pure-grey.jpg', 'Royal Blue': '/images/tata-nexon-royal-blue.jpg', 'Royal Blue With Black Roof': '/images/tata-nexon-royal-blue-with-black-roof.jpg', 'Daytona Grey': '/images/tata-nexon-daytona-grey.jpg'}
_NEXON_MIRROR  = True

_CITY_COLORS   = ['Lunar Silver Metallic', 'Platinum White Pearl', 'Radiant Red Metallic', 'Meteoroid Grey Metallic', 'Obsidian Blue Pearl', 'Crystal Black Pearl']
_CITY_IMGS     = {'Lunar Silver Metallic': '/images/honda-city-lunar-silver-metallic.jpg', 'Platinum White Pearl': '/images/honda-city-platinum-white-pearl.jpg', 'Radiant Red Metallic': '/images/honda-city-radiant-red-metallic.jpg', 'Meteoroid Grey Metallic': '/images/honda-city-meteoroid-grey-metallic.jpg', 'Obsidian Blue Pearl': '/images/honda-city-obsidian-blue-pearl.jpg', 'Crystal Black Pearl': '/images/honda-city-crystal-black-pearl.jpg'}
_CITY_MIRROR   = True

CARS_DATA = [
    {'id':1  , 'brand':'Hyundai'   , 'model_name':'Creta'   , 'series':'E'          , 'trim_name':'E 1.5 Petrol MT'                   , 'car_type':'SUV'          , 'fuel_type':'Petrol'  , 'gearbox_type':'Manual'    , 'ex_showroom_price':11.0  , 'power':113  , 'mirror':_CRETA_MIRROR, 'colors':_CRETA_COLORS, 'image_urls':_CRETA_IMGS},
    {'id':2  , 'brand':'Hyundai'   , 'model_name':'Creta'   , 'series':'EX'         , 'trim_name':'EX 1.5 Petrol MT'                  , 'car_type':'SUV'          , 'fuel_type':'Petrol'  , 'gearbox_type':'Manual'    , 'ex_showroom_price':12.0  , 'power':113  , 'mirror':_CRETA_MIRROR, 'colors':_CRETA_COLORS, 'image_urls':_CRETA_IMGS},
    {'id':3  , 'brand':'Hyundai'   , 'model_name':'Creta'   , 'series':'EX'         , 'trim_name':'EX 1.5 Diesel MT'                  , 'car_type':'SUV'          , 'fuel_type':'Diesel'  , 'gearbox_type':'Manual'    , 'ex_showroom_price':13.2  , 'power':114  , 'mirror':_CRETA_MIRROR, 'colors':_CRETA_COLORS, 'image_urls':_CRETA_IMGS},
    {'id':4  , 'brand':'Hyundai'   , 'model_name':'Creta'   , 'series':'S'          , 'trim_name':'S 1.5 Petrol MT'                   , 'car_type':'SUV'          , 'fuel_type':'Petrol'  , 'gearbox_type':'Manual'    , 'ex_showroom_price':13.16 , 'power':113  , 'mirror':_CRETA_MIRROR, 'colors':_CRETA_COLORS, 'image_urls':_CRETA_IMGS},
    {'id':5  , 'brand':'Hyundai'   , 'model_name':'Creta'   , 'series':'SX'         , 'trim_name':'SX 1.5 Petrol iVT'                 , 'car_type':'SUV'          , 'fuel_type':'Petrol'  , 'gearbox_type':'Automatic' , 'ex_showroom_price':15.82 , 'power':113  , 'mirror':_CRETA_MIRROR, 'colors':_CRETA_COLORS, 'image_urls':_CRETA_IMGS},
    {'id':6  , 'brand':'Hyundai'   , 'model_name':'Creta'   , 'series':'SX'         , 'trim_name':'SX 1.5 Diesel MT'                  , 'car_type':'SUV'          , 'fuel_type':'Diesel'  , 'gearbox_type':'Manual'    , 'ex_showroom_price':17.16 , 'power':114  , 'mirror':_CRETA_MIRROR, 'colors':_CRETA_COLORS, 'image_urls':_CRETA_IMGS},
    {'id':7  , 'brand':'Hyundai'   , 'model_name':'Creta'   , 'series':'SX(O)'      , 'trim_name':'SX(O) 1.5 Diesel AT'               , 'car_type':'SUV'          , 'fuel_type':'Diesel'  , 'gearbox_type':'Automatic' , 'ex_showroom_price':20.15 , 'power':114  , 'mirror':_CRETA_MIRROR, 'colors':_CRETA_COLORS, 'image_urls':_CRETA_IMGS},
    {'id':8  , 'brand':'Hyundai'   , 'model_name':'Creta'   , 'series':'SX(O) Tech' , 'trim_name':'SX(O) Tech 1.5 Turbo Petrol DCT'   , 'car_type':'SUV'          , 'fuel_type':'Petrol'  , 'gearbox_type':'Automatic' , 'ex_showroom_price':20.3  , 'power':158  , 'mirror':_CRETA_MIRROR, 'colors':_CRETA_COLORS, 'image_urls':_CRETA_IMGS},
    {'id':9  , 'brand':'Mahindra'  , 'model_name':'Thar'    , 'series':'MX'         , 'trim_name':'MX 5-seater 2.2 Diesel MT'         , 'car_type':'Off-Road SUV' , 'fuel_type':'Diesel'  , 'gearbox_type':'Manual'    , 'ex_showroom_price':12.99 , 'power':150  , 'mirror':_THAR_MIRROR , 'colors':_THAR_COLORS , 'image_urls':_THAR_IMGS },
    {'id':10 , 'brand':'Mahindra'  , 'model_name':'Thar'    , 'series':'AX'         , 'trim_name':'AX 5-seater 2.2 Diesel MT'         , 'car_type':'Off-Road SUV' , 'fuel_type':'Diesel'  , 'gearbox_type':'Manual'    , 'ex_showroom_price':16.49 , 'power':150  , 'mirror':_THAR_MIRROR , 'colors':_THAR_COLORS , 'image_urls':_THAR_IMGS },
    {'id':11 , 'brand':'Mahindra'  , 'model_name':'Thar'    , 'series':'AX'         , 'trim_name':'AX 5-seater 2.0 Petrol AT'         , 'car_type':'Off-Road SUV' , 'fuel_type':'Petrol'  , 'gearbox_type':'Automatic' , 'ex_showroom_price':17.49 , 'power':175  , 'mirror':_THAR_MIRROR , 'colors':_THAR_COLORS , 'image_urls':_THAR_IMGS },
    {'id':12 , 'brand':'Mahindra'  , 'model_name':'Thar'    , 'series':'LX'         , 'trim_name':'LX 5-seater 2.2 Diesel AT'         , 'car_type':'Off-Road SUV' , 'fuel_type':'Diesel'  , 'gearbox_type':'Automatic' , 'ex_showroom_price':20.49 , 'power':150  , 'mirror':_THAR_MIRROR , 'colors':_THAR_COLORS , 'image_urls':_THAR_IMGS },
    {'id':13 , 'brand':'Mahindra'  , 'model_name':'Thar'    , 'series':'LX'         , 'trim_name':'LX 5-seater 2.0 Petrol AT'         , 'car_type':'Off-Road SUV' , 'fuel_type':'Petrol'  , 'gearbox_type':'Automatic' , 'ex_showroom_price':19.99 , 'power':175  , 'mirror':_THAR_MIRROR , 'colors':_THAR_COLORS , 'image_urls':_THAR_IMGS },
    {'id':14 , 'brand':'Tata'      , 'model_name':'Nexon'   , 'series':'Smart'      , 'trim_name':'Smart 1.2 Petrol MT'               , 'car_type':'Compact SUV'  , 'fuel_type':'Petrol'  , 'gearbox_type':'Manual'    , 'ex_showroom_price':8.15  , 'power':118  , 'mirror':_NEXON_MIRROR, 'colors':_NEXON_COLORS, 'image_urls':_NEXON_IMGS},
    {'id':15 , 'brand':'Tata'      , 'model_name':'Nexon'   , 'series':'Smart+'     , 'trim_name':'Smart+ 1.2 Petrol MT'              , 'car_type':'Compact SUV'  , 'fuel_type':'Petrol'  , 'gearbox_type':'Manual'    , 'ex_showroom_price':9.3   , 'power':118  , 'mirror':_NEXON_MIRROR, 'colors':_NEXON_COLORS, 'image_urls':_NEXON_IMGS},
    {'id':16 , 'brand':'Tata'      , 'model_name':'Nexon'   , 'series':'Pure'       , 'trim_name':'Pure 1.5 Diesel MT'                , 'car_type':'Compact SUV'  , 'fuel_type':'Diesel'  , 'gearbox_type':'Manual'    , 'ex_showroom_price':11.1  , 'power':113  , 'mirror':_NEXON_MIRROR, 'colors':_NEXON_COLORS, 'image_urls':_NEXON_IMGS},
    {'id':17 , 'brand':'Tata'      , 'model_name':'Nexon'   , 'series':'Pure+'      , 'trim_name':'Pure+ 1.5 Diesel MT'               , 'car_type':'Compact SUV'  , 'fuel_type':'Diesel'  , 'gearbox_type':'Manual'    , 'ex_showroom_price':12.0  , 'power':113  , 'mirror':_NEXON_MIRROR, 'colors':_NEXON_COLORS, 'image_urls':_NEXON_IMGS},
    {'id':18 , 'brand':'Tata'      , 'model_name':'Nexon'   , 'series':'Creative'   , 'trim_name':'Creative 1.2 Petrol AMT'           , 'car_type':'Compact SUV'  , 'fuel_type':'Petrol'  , 'gearbox_type':'Automatic' , 'ex_showroom_price':11.8  , 'power':118  , 'mirror':_NEXON_MIRROR, 'colors':_NEXON_COLORS, 'image_urls':_NEXON_IMGS},
    {'id':19 , 'brand':'Tata'      , 'model_name':'Nexon'   , 'series':'Creative+'  , 'trim_name':'Creative+ 1.5 Diesel AMT'          , 'car_type':'Compact SUV'  , 'fuel_type':'Diesel'  , 'gearbox_type':'Automatic' , 'ex_showroom_price':13.1  , 'power':113  , 'mirror':_NEXON_MIRROR, 'colors':_NEXON_COLORS, 'image_urls':_NEXON_IMGS},
    {'id':20 , 'brand':'Tata'      , 'model_name':'Nexon'   , 'series':'Fearless'   , 'trim_name':'Fearless 1.2 Petrol DCT'           , 'car_type':'Compact SUV'  , 'fuel_type':'Petrol'  , 'gearbox_type':'Automatic' , 'ex_showroom_price':14.8  , 'power':118  , 'mirror':_NEXON_MIRROR, 'colors':_NEXON_COLORS, 'image_urls':_NEXON_IMGS},
    {'id':21 , 'brand':'Tata'      , 'model_name':'Nexon'   , 'series':'Fearless S' , 'trim_name':'Fearless S 1.2 Petrol DCT S'       , 'car_type':'Compact SUV'  , 'fuel_type':'Petrol'  , 'gearbox_type':'Automatic' , 'ex_showroom_price':16.49 , 'power':118  , 'mirror':_NEXON_MIRROR, 'colors':_NEXON_COLORS, 'image_urls':_NEXON_IMGS},
    {'id':22 , 'brand':'Honda'     , 'model_name':'City'    , 'series':'V'          , 'trim_name':'V 1.5 Petrol MT'                   , 'car_type':'Sedan'        , 'fuel_type':'Petrol'  , 'gearbox_type':'Manual'    , 'ex_showroom_price':11.48 , 'power':119  , 'mirror':_CITY_MIRROR , 'colors':_CITY_COLORS , 'image_urls':_CITY_IMGS },
    {'id':23 , 'brand':'Honda'     , 'model_name':'City'    , 'series':'V'          , 'trim_name':'V 1.5 Petrol CVT'                  , 'car_type':'Sedan'        , 'fuel_type':'Petrol'  , 'gearbox_type':'Automatic' , 'ex_showroom_price':12.98 , 'power':119  , 'mirror':_CITY_MIRROR , 'colors':_CITY_COLORS , 'image_urls':_CITY_IMGS },
    {'id':24 , 'brand':'Honda'     , 'model_name':'City'    , 'series':'VX'         , 'trim_name':'VX 1.5 Petrol MT'                  , 'car_type':'Sedan'        , 'fuel_type':'Petrol'  , 'gearbox_type':'Manual'    , 'ex_showroom_price':13.98 , 'power':119  , 'mirror':_CITY_MIRROR , 'colors':_CITY_COLORS , 'image_urls':_CITY_IMGS },
    {'id':25 , 'brand':'Honda'     , 'model_name':'City'    , 'series':'VX'         , 'trim_name':'VX 1.5 Petrol CVT'                 , 'car_type':'Sedan'        , 'fuel_type':'Petrol'  , 'gearbox_type':'Automatic' , 'ex_showroom_price':15.4  , 'power':119  , 'mirror':_CITY_MIRROR , 'colors':_CITY_COLORS , 'image_urls':_CITY_IMGS },
    {'id':26 , 'brand':'Honda'     , 'model_name':'City'    , 'series':'ZX'         , 'trim_name':'ZX 1.5 Petrol CVT'                 , 'car_type':'Sedan'        , 'fuel_type':'Petrol'  , 'gearbox_type':'Automatic' , 'ex_showroom_price':15.42 , 'power':119  , 'mirror':_CITY_MIRROR , 'colors':_CITY_COLORS , 'image_urls':_CITY_IMGS },
    {'id':27 , 'brand':'Honda'     , 'model_name':'City'    , 'series':'e:HEV'      , 'trim_name':'e:HEV 1.5 Strong Hybrid e-CVT'     , 'car_type':'Sedan'        , 'fuel_type':'Hybrid'  , 'gearbox_type':'Automatic' , 'ex_showroom_price':18.99 , 'power':126  , 'mirror':_CITY_MIRROR , 'colors':_CITY_COLORS , 'image_urls':_CITY_IMGS },
]
